package md;

class Unpack {
	@:md.body("	register const u8* held __asm__(\"a0\") = (const u8*)from;
	register u8* grown __asm__(\"a1\") = (u8*)into;

	__asm__ __volatile__ (
		\"	.macro	APLIB_BIT\\n\"
		\"	add.b	%%d3,%%d3\\n\"
		\"	bne.s	9f\\n\"
		\"	move.b	(%%a0)+,%%d3\\n\"
		\"	addx.b	%%d3,%%d3\\n\"
		\"9:\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	.macro	APLIB_GAMMA\\n\"
		\"	moveq	#1,%%d2\\n\"
		\"8:\\n\"
		\"	APLIB_BIT\\n\"
		\"	addx.l	%%d2,%%d2\\n\"
		\"	APLIB_BIT\\n\"
		\"	bcs.s	8b\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	moveq	#-128,%%d3\\n\"
		\"	moveq	#0,%%d4\\n\"
		\"	lea	32000.w,%%a3\\n\"
		\"	lea	1280.w,%%a4\\n\"
		\"	lea	128.w,%%a5\\n\"
		\"	move.b	(%%a0)+,(%%a1)+\\n\"
		\"	moveq	#2,%%d1\\n\"
		\"\\n\"
		\"Lapnext:\\n\"
		\"	APLIB_BIT\\n\"
		\"	bcs.s	Lapnotliteral\\n\"
		\"	moveq	#2,%%d1\\n\"
		\"Lapliteral:\\n\"
		\"	move.b	(%%a0)+,(%%a1)+\\n\"
		\"	APLIB_BIT\\n\"
		\"	bcc.s	Lapliteral\\n\"
		\"\\n\"
		\"Lapnotliteral:\\n\"
		\"	APLIB_BIT\\n\"
		\"	bcc.w	Lapcodepair\\n\"
		\"	moveq	#0,%%d0\\n\"
		\"	APLIB_BIT\\n\"
		\"	bcc.s	Lapshortmatch\\n\"
		\"\\n\"
		\"	moveq	#3,%%d5\\n\"
		\"Lapfourbits:\\n\"
		\"	APLIB_BIT\\n\"
		\"	roxl.l	#1,%%d0\\n\"
		\"	dbf	%%d5,Lapfourbits\\n\"
		\"	beq.s	Lapwritebyte\\n\"
		\"	move.l	%%a1,%%a2\\n\"
		\"	suba.l	%%d0,%%a2\\n\"
		\"	move.b	(%%a2),%%d0\\n\"
		\"Lapwritebyte:\\n\"
		\"	move.b	%%d0,(%%a1)+\\n\"
		\"	moveq	#2,%%d1\\n\"
		\"	bra.w	Lapnext\\n\"
		\"\\n\"
		\"Lapshortmatch:\\n\"
		\"	moveq	#3,%%d2\\n\"
		\"	move.b	(%%a0)+,%%d0\\n\"
		\"	lsr.b	#1,%%d0\\n\"
		\"	beq.w	Lapdone\\n\"
		\"	bcs.w	Lapnewlast\\n\"
		\"	moveq	#2,%%d2\\n\"
		\"	bra.w	Lapnewlast\\n\"
		\"\\n\"
		\"Lapcodepair:\\n\"
		\"	APLIB_GAMMA\\n\"
		\"	sub.l	%%d1,%%d2\\n\"
		\"	bne.s	Lapnormalpair\\n\"
		\"	move.l	%%d4,%%d0\\n\"
		\"	APLIB_GAMMA\\n\"
		\"	bra.s	Lapcopypair\\n\"
		\"\\n\"
		\"Lapnormalpair:\\n\"
		\"	subq.l	#1,%%d2\\n\"
		\"	lsl.l	#8,%%d2\\n\"
		\"	move.b	(%%a0)+,%%d2\\n\"
		\"	move.l	%%d2,%%d0\\n\"
		\"	APLIB_GAMMA\\n\"
		\"	cmp.l	%%a3,%%d0\\n\"
		\"	bge.s	Laptwoinc\\n\"
		\"	cmp.l	%%a4,%%d0\\n\"
		\"	bge.s	Laponeinc\\n\"
		\"	cmp.l	%%a5,%%d0\\n\"
		\"	bge.s	Lapnewlast\\n\"
		\"Laptwoinc:\\n\"
		\"	addq.l	#1,%%d2\\n\"
		\"Laponeinc:\\n\"
		\"	addq.l	#1,%%d2\\n\"
		\"Lapnewlast:\\n\"
		\"	move.l	%%d0,%%d4\\n\"
		\"Lapcopypair:\\n\"
		\"	subq.l	#1,%%d2\\n\"
		\"	move.l	%%a1,%%a2\\n\"
		\"	suba.l	%%d0,%%a2\\n\"
		\"Lapcopyloop:\\n\"
		\"	move.b	(%%a2)+,(%%a1)+\\n\"
		\"	dbf	%%d2,Lapcopyloop\\n\"
		\"	moveq	#1,%%d1\\n\"
		\"	bra.w	Lapnext\\n\"
		\"\\n\"
		\"Lapdone:\\n\"
		\"	.purgem	APLIB_BIT\\n\"
		\"	.purgem	APLIB_GAMMA\\n\"
		: \"+a\" (held), \"+a\" (grown)
		:
		: \"d0\", \"d1\", \"d2\", \"d3\", \"d4\", \"d5\", \"a2\", \"a3\", \"a4\", \"a5\", \"memory\", \"cc\"
	);

	return (s32)grown - into;")
	public static function aplib(from:Int, into:Int):Int {
		return 0;
	}

	@:md.body("	register const u8* held __asm__(\"a0\") = (const u8*)from;
	register u8* grown __asm__(\"a1\") = (u8*)into;

	__asm__ __volatile__ (
		\"	.macro	LZ4W_NEXT\\n\"
		\"	moveq	#0,%%d1\\n\"
		\"	moveq	#0,%%d0\\n\"
		\"	move.b	(%%a0)+,%%d0\\n\"
		\"	move.b	(%%a0)+,%%d1\\n\"
		\"	add.w	%%d0,%%d0\\n\"
		\"	add.w	%%d0,%%d0\\n\"
		\"	jmp	(%%a3,%%d0.w)\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	.macro	LZ4W_MATCH words\\n\"
		\"	add.w	%%d1,%%d1\\n\"
		\"	neg.w	%%d1\\n\"
		\"	lea	-2(%%a1,%%d1.w),%%a2\\n\"
		\"	.rept	((\\\\words)+1)\\n\"
		\"	move.w	(%%a2)+,(%%a1)+\\n\"
		\"	.endr\\n\"
		\"	LZ4W_NEXT\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	.macro	LZ4W_LONG\\n\"
		\"	move.w	(%%a0)+,%%d0\\n\"
		\"	add.w	%%d0,%%d0\\n\"
		\"	bcs.w	Lfromsource\\n\"
		\"	lea	-2(%%a1,%%d0.w),%%a2\\n\"
		\"	neg.w	%%d1\\n\"
		\"	jmp	(%%a4,%%d1.w)\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	.macro	LZ4W_GROUP match\\n\"
		\"Lliteral14match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral12match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral10match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral8match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral6match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral4match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral2match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral0match\\\\match:\\n\"
		\"	LZ4W_MATCH \\\\match\\n\"
		\"Lliteral15match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral13match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral11match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral9match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral7match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral5match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral3match\\\\match:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral1match\\\\match:	move.w	(%%a0)+,(%%a1)+\\n\"
		\"	LZ4W_MATCH \\\\match\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	.macro	LZ4W_ROW literal\\n\"
		\"	.irp	match,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15\\n\"
		\"	bra.w	Lliteral\\\\literal\\\\()match\\\\match\\n\"
		\"	.endr\\n\"
		\"	.endm\\n\"
		\"\\n\"
		\"	lea	Ltable(%%pc),%%a3\\n\"
		\"	lea	Lmatchlength(%%pc),%%a4\\n\"
		\"	LZ4W_NEXT\\n\"
		\"\\n\"
		\"Ltable:\\n\"
		\"	LZ4W_ROW 0\\n\"
		\"	LZ4W_ROW 1\\n\"
		\"	LZ4W_ROW 2\\n\"
		\"	LZ4W_ROW 3\\n\"
		\"	LZ4W_ROW 4\\n\"
		\"	LZ4W_ROW 5\\n\"
		\"	LZ4W_ROW 6\\n\"
		\"	LZ4W_ROW 7\\n\"
		\"	LZ4W_ROW 8\\n\"
		\"	LZ4W_ROW 9\\n\"
		\"	LZ4W_ROW 10\\n\"
		\"	LZ4W_ROW 11\\n\"
		\"	LZ4W_ROW 12\\n\"
		\"	LZ4W_ROW 13\\n\"
		\"	LZ4W_ROW 14\\n\"
		\"	LZ4W_ROW 15\\n\"
		\"\\n\"
		\"	.irp	match,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15\\n\"
		\"	LZ4W_GROUP \\\\match\\n\"
		\"	.endr\\n\"
		\"\\n\"
		\"Lliteral14match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral12match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral10match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral8match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral6match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral4match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral2match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"	add.w	%%d1,%%d1\\n\"
		\"	beq.w	Lnext\\n\"
		\"	LZ4W_LONG\\n\"
		\"\\n\"
		\"Lliteral15match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral13match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral11match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral9match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral7match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral5match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral3match0:	move.l	(%%a0)+,(%%a1)+\\n\"
		\"Lliteral1match0:	move.w	(%%a0)+,(%%a1)+\\n\"
		\"	add.w	%%d1,%%d1\\n\"
		\"	beq.w	Lnext\\n\"
		\"	LZ4W_LONG\\n\"
		\"\\n\"
		\"Lliteral0match0:\\n\"
		\"	add.w	%%d1,%%d1\\n\"
		\"	beq.w	Ldone\\n\"
		\"	LZ4W_LONG\\n\"
		\"\\n\"
		\"Lfromsource:\\n\"
		\"	lea	-2(%%a0,%%d0.w),%%a2\\n\"
		\"	lsr.w	#1,%%d1\\n\"
		\"	addq.w	#1,%%d1\\n\"
		\"Lfromsourceloop:\\n\"
		\"	move.w	(%%a2)+,(%%a1)+\\n\"
		\"	dbra	%%d1,Lfromsourceloop\\n\"
		\"	LZ4W_NEXT\\n\"
		\"\\n\"
		\"	.rept	255\\n\"
		\"	move.w	(%%a2)+,(%%a1)+\\n\"
		\"	.endr\\n\"
		\"Lmatchlength:\\n\"
		\"	move.w	(%%a2)+,(%%a1)+\\n\"
		\"	move.w	(%%a2)+,(%%a1)+\\n\"
		\"	moveq	#0,%%d1\\n\"
		\"Lnext:\\n\"
		\"	moveq	#0,%%d0\\n\"
		\"	move.b	(%%a0)+,%%d0\\n\"
		\"	move.b	(%%a0)+,%%d1\\n\"
		\"	add.w	%%d0,%%d0\\n\"
		\"	add.w	%%d0,%%d0\\n\"
		\"	jmp	(%%a3,%%d0.w)\\n\"
		\"\\n\"
		\"Ldone:\\n\"
		\"	move.w	(%%a0)+,%%d0\\n\"
		\"	bpl.s	Lnobyte\\n\"
		\"	move.b	%%d0,(%%a1)+\\n\"
		\"Lnobyte:\\n\"
		\"	.purgem	LZ4W_NEXT\\n\"
		\"	.purgem	LZ4W_MATCH\\n\"
		\"	.purgem	LZ4W_LONG\\n\"
		\"	.purgem	LZ4W_GROUP\\n\"
		\"	.purgem	LZ4W_ROW\\n\"
		: \"+a\" (held), \"+a\" (grown)
		:
		: \"d0\", \"d1\", \"a2\", \"a3\", \"a4\", \"memory\", \"cc\"
	);

	return (s32)grown - into;")
	public static function lz4w(from:Int, into:Int):Int {
		return 0;
	}
}
